#pragma once
#include <Game/ShipInfo.h>




struct global_status
{
    int* field_0;
    int* field_4;
    int field_8;
    int* field_C; //custom array, field_C -> 0 = count, 4 = pointer
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int* m_pSystemMapLinesInfo; // CustomArray<unsigned int>*
    int* field_28;
    int* field_2C;
    int* field_30;
    int* field_34;
    int* field_38;
    int* field_3C;
    int* field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
    int* field_58;
    int field_5C;
    int field_60;
    int field_64;
    int field_68;
    int field_6C;
    int* m_pShipItems; //CustomArray<Item>*
    int field_74;
    int field_78;
    int field_7C;
    int field_80;
    int field_84;
    int field_88;
    int field_8C;
    int field_90;
    int field_94;
    int field_98;
    int field_9C;
    int field_A0;
    int field_A4;
    int field_A8;
    int field_AC;
    int field_B0;
    int field_B4;
    int field_B8;
    int field_BC;
    int field_C0;
    int field_C4;
    int field_C8;
    int field_CC;
    int field_D0;
    int field_D4;
    int field_D8;
    int field_DC;
    int field_E0;
    int field_E4;
    int field_E8;
    int field_EC;
    int field_F0;
    int field_F4;
    int field_F8;
    int field_FC;
    int field_100;
    int field_104;
    int field_108;
    int field_10C;
    int field_110;
    int field_114;
    int field_118;
    int field_11C;
    int field_120;
    int field_124;
    int field_128;
    int field_12C;
    int field_130;
    int field_134;
    int field_138;
    int field_13C;
    int field_140;
    int field_144;
    int field_148;
    int field_14C;
    int field_150;
    ShipInfo* m_pShipInfo;
    int* field_158;
    int* field_15C;
    int* m_pStationInfo; //StationInfo
    int field_164;
    int* m_pCurrentPlayerSystemInfo;
    int field_16C;
    int field_170;
    int m_nMoney;
    int field_178;
    int field_17C;
    int field_180;
    int field_184;
    int m_nEnemiesKilled;
    int field_18C;
    int m_nPlayerLevel;
    int field_194;
    int m_nVisitedStations;
    int field_19C;
    int field_1A0;
    int field_1A4;
    int field_1A8;
    int field_1AC;
    int m_nCurrentCampaignMission;
    int field_1B4;
    int field_1B8;
    int field_1BC;
    int field_1C0;
    int field_1C4;
    int field_1C8;
    int field_1CC;
    int field_1D0;
    int field_1D4;
    int field_1D8;
    int field_1DC;
    int field_1E0;
    int field_1E4;
    int field_1E8;
    int field_1EC;
    int field_1F0;
    int field_1F4;
};

static inline global_status* globalStatus = 0;
